In [2]:
import pandas as pd

#read and parse the training set .csv features file 
df = pd.read_csv('Datasets/A3-data.txt', delimiter = ',')

X = df[['x', 'y', 'z', 't']]
y = df[['class']]
y = y.to_numpy().flatten()
print(X.to_numpy())

[[-3.16755250e-02 -9.91205374e+00 -5.79436176e-01 -1.04423881e+00]
 [ 2.52598694e-03  6.17245598e+00  3.28833907e+00 -1.00642749e+00]
 [ 1.83123266e-01 -3.87840555e-01  6.23646977e+00 -1.69149115e+00]
 ...
 [-6.68528740e-01 -6.07597209e-01  6.39294699e-01  4.32921341e+00]
 [-1.22710839e-01 -5.51695654e+00 -2.11117254e+00  2.20967467e+00]
 [ 7.40207379e-01 -7.49217616e+00  1.95942618e+00 -7.11991799e+00]]


In [16]:
from sklearn_som.som import SOM
import numpy as np
import matplotlib.pyplot as plt

#initialize
som_model = SOM(m = 10, n = 10 , dim = 4)
som_model.
#fit
som_model.fit(X.to_numpy())
print(X.shape)

#predict
predicted_data = som_model.predict(X.to_numpy())
print("labels_map : ", predicted_data.)
print(predicted_data.shape)
#transform
transformed_data = som_model.transform(X)
print(transformed_data.shape)

print(transformed_data)

(360, 4)
labels_map :  [22 67 70 26 80 69 78 69 78 49 64 52  3 63 70 75 75 90  1 54 47 32 74 90
 52 68 69  0 72 23 10 49 87 83 97 80 94 91 90 50 90 34 73 86 90 94 91 87
 78 90 79 84 95 97 78 67 95 51 10 47 77 49 56 27 64 10 83 57 63 80 64 32
 79 21 83 36 63 87 22 72 92 91 77 58 77 86 89 83 74 89 10 66 98 50 44  9
 76 80 74 93 59 91 51 57 83 52 57 26 73 67 73 60 88 57 54  1 83 78 90 57
 83 87 94 74 59 67 54 91 57  8 78 59 46 85 56 80 91 63 70 99 90 93 57 97
 65 58 66 88  0 97 54 47 48 41  8 10 69 51 76  0 12 99 50 10 13 51 96 72
 52 39 44 42 37 80 64 62 26 61 77 72 63 95 68 94  0 93 30 93 59 74 37 58
 70 98 28 37 72 94 90 91 48 47 81 90 77 67 58 23  0 69 54 32 83 62 81 85
 90 22  1 90 94 90 70 75 48 45 10 10 99 91 62 74 80 97 58 50 10 75 64 64
 24 60 77 52 99 64 75 93 93 54 60 90 90 91 85 49 73 10 51 21 10 74 90 90
  1 62 31 64 85 73 10 90 10 85 65 82 42 45 67 94 83 67 77 80 76 52 69  0
 99 10 80 78 68 22 34 67 52 26 72 14 59 77 93 12 23 72 84 26 64 86 42 19
 50 90 90 95 99 70 95 12 57 

In [8]:
import numpy as np

arr = [1, 5, 3, 7, 2]
max_index = np.argmax(arr)
print(max_index)

3
